import { useEffect, useState } from 'react'
import { facilitatorEvaluationApi } from '../../monitoring/api/facilitatorEvaluationApi'
import { ApiError, Empty, Loading } from '../../monitoring/pages/MonitoringPage'
import { Avatar } from '../../search/pages/SearchPage'

export function CompetencyProfilePage({ selectedFacilitatorId, onNavigate }) {
  const [state, setState] = useState({ loading: false, error: '', data: null })
  const load = () => { if (!selectedFacilitatorId) return; setState({ loading: true, error: '', data: null }); facilitatorEvaluationApi.getCompetencyProfile(selectedFacilitatorId).then((data) => setState({ loading: false, error: '', data })).catch((error) => setState({ loading: false, error: error.message, data: null })) }
  useEffect(load, [selectedFacilitatorId])
  if (!selectedFacilitatorId) return <section className="module-page page-enter"><Empty text="Pilih fasilitator dari halaman pencarian atau monitoring." /><button className="primary-button" onClick={() => onNavigate('pencarian')}>Cari Fasilitator</button></section>
  if (state.loading) return <Loading text="Memuat profil kompetensi..." />
  if (state.error) return <ApiError message={state.error} />
  if (!state.data) return null
  const person = state.data
  return <section className="module-page page-enter"><button className="text-button" onClick={() => onNavigate('pencarian')}>← Kembali ke pencarian</button><div className="profile-hero"><Avatar person={person} large /><div><p className="eyebrow">PROFIL KOMPETENSI</p><h2>{person.name}</h2><p>{person.degree} · {person.position} · {person.unit}</p><div className="profile-rating">★ {person.rating?.average ?? '—'} <span>({person.rating?.count ?? 0} ulasan)</span></div></div></div><div className="profile-grid"><Info title="Biodata" rows={[['TTL', person.birthInfo], ['NIP', person.nip], ['Email', person.email], ['No. HP', person.phone], ['Unit kerja', person.unit], ['Jabatan', person.position]]} /><Info title="Kompetensi"><div className="tag-list">{person.competencies?.length ? person.competencies.map((item) => <span key={item}>{item}</span>) : 'Belum ada kompetensi'}</div></Info><Info title="Dokumen"><div className="document-links">{Object.entries(person.documents || {}).map(([name, url]) => url ? <a key={name} href={url} target="_blank" rel="noreferrer">↗ {name}</a> : <span key={name}>— {name} belum tersedia</span>)}</div></Info><Info title="Riwayat pelatihan">{person.trainings?.length ? person.trainings.map((item) => <div className="training-item" key={item.id}><b>{item.name}</b><span>{item.material} · {item.date} · {item.organizer}</span></div>) : <p className="muted">Belum ada riwayat pelatihan.</p>}</Info><ReviewPanel person={person} onSaved={load} /></div></section>
}
function Info({ title, rows = [], children }) { return <section className="profile-panel"><h3>{title}</h3>{rows.map(([label, value]) => <div className="info-row" key={label}><span>{label}</span><b>{value || '—'}</b></div>)}{children}</section> }
function ReviewPanel({ person, onSaved }) { const [rating, setRating] = useState('5'); const [comment, setComment] = useState(''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const save = async (event) => { event.preventDefault(); const score = Number(rating); if (score < 1 || score > 5 || !comment.trim()) return setError('Rating 1–5 dan ulasan wajib diisi.'); setSaving(true); setError(''); try { await facilitatorEvaluationApi.createReview(person.id, { rating: score, comment: comment.trim() }); setComment(''); onSaved() } catch (requestError) { setError(requestError.message) } finally { setSaving(false) } }; return <section className="profile-panel review-panel"><h3>Rating & ulasan</h3><form onSubmit={save}><div className="review-fields"><select value={rating} onChange={(e) => setRating(e.target.value)}>{[5, 4, 3, 2, 1].map((value) => <option key={value} value={value}>{value} bintang</option>)}</select><input value={comment} onChange={(e) => setComment(e.target.value)} placeholder="Tulis ulasan" /><button className="primary-button" disabled={saving}>{saving ? 'Menyimpan...' : 'Kirim'}</button></div>{error && <small className="form-error">{error}</small>}</form><div className="review-list">{person.reviews?.length ? person.reviews.map((review) => <article key={review.id}><b>★ {review.rating}</b><p>{review.comment}</p><small>{review.authorName} · {review.createdAt}</small></article>) : <p className="muted">Belum ada ulasan.</p>}</div></section> }
