import { useState } from 'react'
import { facilitatorEvaluationApi } from '../../monitoring/api/facilitatorEvaluationApi'
import { ApiError, Empty, Loading } from '../../monitoring/pages/MonitoringPage'
import { resolveAssetUrl } from '../../../shared/utils/resolveAssetUrl'

export function SearchPage({ onSelectFacilitator }) {
  const [filters, setFilters] = useState({ query: '', competency: '', min_rating: '', status: '' })
  const [state, setState] = useState({ loading: false, error: '', records: null })
  const update = (name) => (event) => setFilters({ ...filters, [name]: event.target.value })
  const submit = async (event) => { event.preventDefault(); setState({ loading: true, error: '', records: null }); try { const payload = await facilitatorEvaluationApi.searchFacilitators(filters); setState({ loading: false, error: '', records: payload.data || payload }) } catch (error) { setState({ loading: false, error: error.message, records: [] }) } }
  return <section className="module-page page-enter"><header className="module-heading"><p className="eyebrow">PENCARIAN FASILITATOR</p><h2>Temukan fasilitator yang tepat</h2><p>Filter dikirim langsung ke API, bukan seluruh data difilter di browser.</p></header><form className="search-form" onSubmit={submit}><input placeholder="Nama fasilitator" value={filters.query} onChange={update('query')} /><input placeholder="Materi / kompetensi" value={filters.competency} onChange={update('competency')} /><select value={filters.min_rating} onChange={update('min_rating')}><option value="">Semua rating</option><option value="4">Rating 4+</option><option value="3">Rating 3+</option></select><select value={filters.status} onChange={update('status')}><option value="">Semua status</option><option value="active">Aktif</option><option value="inactive">Tidak aktif</option></select><button className="primary-button">Cari</button></form>{state.loading ? <Loading text="Mencari fasilitator..." /> : state.error ? <ApiError message={state.error} /> : state.records === null ? <Empty text="Masukkan kriteria, lalu tekan Cari." /> : !state.records.length ? <Empty text="Tidak ada fasilitator yang sesuai filter." /> : <div className="facilitator-grid">{state.records.map((person) => <article className="facilitator-card" key={person.id}><Avatar person={person} /><h3>{person.name}</h3><span className={`badge ${person.status === 'active' ? 'complete' : 'missing'}`}>{person.statusLabel || person.status || '—'}</span><p className="competencies">{person.competencies?.map((item) => typeof item === 'string' ? item : item.name).join(' · ') || 'Kompetensi belum tersedia'}</p><div className="person-metrics"><span>★ {person.averageRating ?? '—'}</span><span>{person.trainingCount ?? '—'} pelatihan</span></div><button className="outline-button" onClick={() => onSelectFacilitator(person.id)}>Lihat profil</button></article>)}</div>}</section>
}
export function Avatar({ person, large = false }) { return <div className={large ? 'large-avatar' : 'person-avatar'}>{person.photoUrl ? <img src={resolveAssetUrl(person.photoUrl)} alt="" /> : person.name?.slice(0, 2)}</div> }