import { createServer } from 'node:http'
import { scryptSync, randomBytes, timingSafeEqual } from 'node:crypto'
import { mkdirSync, writeFileSync, readFileSync, existsSync } from 'node:fs'
import { extname, join, normalize as normalizePath } from 'node:path'
import { dirname, relative, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import './database/database.js'
import { db } from './database/database.js'
import { createToken, verifyToken } from './lib/auth.js'
import { json, readJson, route } from './lib/http.js'
import { validateFacilitator, validateReview, validateTraining, validateEducation } from './lib/validation.js'
import * as facilitators from './repositories/facilitatorRepository.js'

const port = Number(process.env.API_PORT || 8000)
const required = process.env.AUTH_REQUIRED === 'true'
const hash = (password, salt = randomBytes(16).toString('hex')) => `${salt}:${scryptSync(password, salt, 64).toString('hex')}`
const matches = (password, value) => { const [salt, stored] = value.split(':'); const actual = scryptSync(password, salt, 64).toString('hex'); return timingSafeEqual(Buffer.from(actual, 'hex'), Buffer.from(stored, 'hex')) }
const access = (request) => verifyToken(request.headers.authorization)
const protect = (request, response) => { if (!required) return true; if (access(request)) return true; json(response, 401, { message: 'Autentikasi diperlukan.' }); return false }
const invalid = (response, errors) => json(response, 422, { message: 'Validasi gagal.', errors })
const projectDirectory = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const uploadDirectory = resolve(process.env.UPLOAD_DIRECTORY || join(projectDirectory, 'storage', 'uploads'))
mkdirSync(uploadDirectory, { recursive: true })
async function readMultipart(request) { const maxBytes = Number(process.env.MAX_UPLOAD_BYTES || 10 * 1024 * 1024); if (Number(request.headers['content-length'] || 0) > maxBytes) throw Object.assign(new Error('Ukuran file melebihi batas upload.'), { status: 413 }); const chunks = []; let total = 0; for await (const chunk of request) { total += chunk.length; if (total > maxBytes) throw Object.assign(new Error('Ukuran file melebihi batas upload.'), { status: 413 }); chunks.push(chunk) } const body = Buffer.concat(chunks); const boundary = request.headers['content-type']?.match(/boundary=(?:"([^"]+)"|([^;]+))/)?.[1] || request.headers['content-type']?.match(/boundary=(?:"([^"]+)"|([^;]+))/)?.[2]; if (!boundary) throw Object.assign(new Error('Boundary multipart tidak ditemukan.'), { status: 400 }); const marker = Buffer.from(`--${boundary}`); const result = {}; let cursor = body.indexOf(marker); while (cursor >= 0) { const start = cursor + marker.length + 2; const next = body.indexOf(marker, start); if (next < 0) break; const part = body.subarray(start, next - 2); const split = part.indexOf(Buffer.from('\r\n\r\n')); if (split < 0) { cursor = next; continue } const headers = part.subarray(0, split).toString(); const content = part.subarray(split + 4); const name = headers.match(/name="([^"]+)"/)?.[1]; const filename = headers.match(/filename="([^"]*)"/)?.[1]; if (name && filename) result[name] = { filename, content }; else if (name) result[name] = content.toString(); cursor = next } return result }
function saveUpload(file, kind) { if (!file?.content?.length) throw Object.assign(new Error('File upload wajib diisi.'), { status: 422 }); const extension = extname(file.filename).toLowerCase() || (kind === 'photo' ? '.jpg' : '.png'); const allowedExtensions = ['certificate', 'supporting'].includes(kind) ? ['.pdf', '.jpg', '.jpeg', '.png', '.webp'] : ['.jpg', '.jpeg', '.png', '.webp']; if (!allowedExtensions.includes(extension)) throw Object.assign(new Error(['certificate', 'supporting'].includes(kind) ? 'Format file harus PDF, JPG, PNG, atau WEBP.' : 'Format file harus JPG, PNG, atau WEBP.'), { status: 422 }); const signature = file.content.subarray(0, 8); const isPdf = signature.subarray(0, 5).toString() === '%PDF-'; const isPng = signature.subarray(0, 8).equals(Buffer.from([137, 80, 78, 71, 13, 10, 26, 10])); const isJpeg = signature.subarray(0, 3).equals(Buffer.from([255, 216, 255])); const isWebp = signature.subarray(0, 4).toString() === 'RIFF' && file.content.subarray(8, 12).toString() === 'WEBP'; const validSignature = extension === '.pdf' ? isPdf : extension === '.png' ? isPng : extension === '.webp' ? isWebp : isJpeg; if (!validSignature) throw Object.assign(new Error('Isi file tidak sesuai dengan ekstensi yang digunakan.'), { status: 422 }); const filename = `${kind}-${Date.now()}-${randomBytes(6).toString('hex')}${extension}`; writeFileSync(join(uploadDirectory, filename), file.content); return `/uploads/${filename}` }

const server = createServer(async (request, response) => {
  if (request.method === 'OPTIONS') return json(response, 204, {})
  const url = new URL(request.url, `http://${request.headers.host}`)
  try {
    if (request.method === 'GET' && url.pathname === '/api/health') return json(response, 200, { status: 'ok' })
    if (request.method === 'GET' && url.pathname === '/api/dashboard') return json(response, 200, { data: facilitators.dashboardSummary() })
    if (request.method === 'POST' && url.pathname === '/api/auth/setup') {
      if (db.prepare('SELECT COUNT(*) count FROM users').get().count) return json(response, 409, { message: 'Admin awal sudah pernah dibuat.' })
      const input = await readJson(request); if (!input.name?.trim() || !input.email?.trim() || !input.password || input.password.length < 8) return invalid(response, { setup: 'Nama, email, dan password minimal 8 karakter wajib diisi.' })
      const user = db.prepare('INSERT INTO users (name, email, password_hash, role) VALUES (?, ?, ?, ?)').run(input.name.trim(), input.email.trim().toLowerCase(), hash(input.password), 'admin')
      return json(response, 201, { token: createToken({ id: Number(user.lastInsertRowid), name: input.name.trim(), role: 'admin' }) })
    }
    if (request.method === 'POST' && url.pathname === '/api/auth/login') {
      const input = await readJson(request); const user = db.prepare('SELECT * FROM users WHERE email = ?').get(input.email?.trim().toLowerCase()); if (!user || !matches(input.password || '', user.password_hash)) return json(response, 401, { message: 'Email atau password salah.' })
      return json(response, 200, { token: createToken(user), user: { id: user.id, name: user.name, role: user.role } })
    }
    if (request.method === 'GET' && url.pathname === '/api/auth/me') { if (!protect(request, response)) return; const user = access(request); const data = db.prepare('SELECT id, name, email, role, created_at createdAt FROM users WHERE id = ?').get(user.id); return data ? json(response, 200, { data }) : json(response, 404, { message: 'Admin tidak ditemukan.' }) }
    if (request.method === 'PUT' && url.pathname === '/api/auth/me') { if (!protect(request, response)) return; const user = access(request); const input = await readJson(request); if (!input.name?.trim() || !/^\S+@\S+\.\S+$/.test(input.email || '')) return invalid(response, { profile: 'Nama dan email valid wajib diisi.' }); try { db.prepare('UPDATE users SET name = ?, email = ? WHERE id = ?').run(input.name.trim(), input.email.trim().toLowerCase(), user.id); const data = db.prepare('SELECT id, name, email, role, created_at createdAt FROM users WHERE id = ?').get(user.id); return json(response, 200, { data: { ...data, token: createToken(data) } }) } catch (error) { if (String(error.message).includes('UNIQUE')) return invalid(response, { email: 'Email sudah digunakan.' }); throw error } }
    if (request.method === 'POST' && url.pathname === '/api/auth/change-password') { if (!protect(request, response)) return; const user = access(request); const input = await readJson(request); const current = db.prepare('SELECT password_hash FROM users WHERE id = ?').get(user.id); if (!current || !matches(input.currentPassword || '', current.password_hash)) return json(response, 422, { message: 'Password saat ini salah.' }); if (!input.newPassword || input.newPassword.length < 8) return invalid(response, { password: 'Password baru minimal 8 karakter.' }); db.prepare('UPDATE users SET password_hash = ? WHERE id = ?').run(hash(input.newPassword), user.id); return json(response, 200, { data: { changed: true } }) }
    if (request.method === 'GET' && url.pathname === '/api/settings') { if (!protect(request, response)) return; const rows = db.prepare('SELECT key, value FROM app_settings ORDER BY key').all(); return json(response, 200, { data: Object.fromEntries(rows.map((row) => [row.key, ['maxUploadMb'].includes(row.key) ? Number(row.value) : row.value])) }) }
    if (request.method === 'PUT' && url.pathname === '/api/settings') { if (!protect(request, response)) return; const input = await readJson(request); const allowed = ['institutionName', 'logoUrl', 'cvTemplate', 'maxUploadMb', 'documentCategories']; for (const key of allowed) if (input[key] !== undefined) db.prepare('INSERT INTO app_settings (key, value, updated_at) VALUES (?, ?, CURRENT_TIMESTAMP) ON CONFLICT(key) DO UPDATE SET value = excluded.value, updated_at = CURRENT_TIMESTAMP').run(key, String(input[key])); const rows = db.prepare('SELECT key, value FROM app_settings ORDER BY key').all(); return json(response, 200, { data: Object.fromEntries(rows.map((row) => [row.key, row.key === 'maxUploadMb' ? Number(row.value) : row.value])) }) }
    if (request.method === 'GET' && url.pathname === '/api/facilitators/monitoring') return json(response, 200, { data: facilitators.monitoring(url.searchParams.get('filter') || '') })
    if (request.method === 'GET' && url.pathname === '/api/facilitators/search') return json(response, 200, { data: facilitators.search(Object.fromEntries(url.searchParams)) })
    if (request.method === 'GET' && url.pathname === '/api/facilitators') return json(response, 200, { data: facilitators.listFacilitators() })
    if (request.method === 'GET' && url.pathname === '/api/training-subjects') return json(response, 200, { data: facilitators.listTrainingSubjects() })
    if (request.method === 'POST' && url.pathname === '/api/training-subjects') { if (!protect(request, response)) return; const input = await readJson(request); return json(response, 201, { data: facilitators.createTrainingSubject(input.name) }) }
    const uploadId = route(url, /^\/api\/facilitators\/(\d+)\/(photo|signature|supporting)$/)
    if (request.method === 'POST' && uploadId) { if (!protect(request, response)) return; const person = facilitators.getFacilitator(Number(uploadId[0])); if (!person) return json(response, 404, { message: 'Fasilitator tidak ditemukan.' }); const parts = await readMultipart(request); const value = saveUpload(parts.file, uploadId[1]); const data = uploadId[1] === 'supporting' ? facilitators.createSupportingDocument(Number(uploadId[0]), { url: value, name: parts.name, notes: parts.notes }) : facilitators.updateFacilitator(Number(uploadId[0]), { [uploadId[1] === 'photo' ? 'photoUrl' : 'signatureUrl']: value }); return json(response, 200, { data }) }
    const certificatesRoute = route(url, /^\/api\/facilitators\/(\d+)\/certificates(?:\/(\d+))?$/)
    if (certificatesRoute && request.method === 'GET' && !certificatesRoute[1]) { const data = facilitators.listCertificates(Number(certificatesRoute[0])); return data ? json(response, 200, { data }) : json(response, 404, { message: 'Fasilitator tidak ditemukan.' }) }
    if (certificatesRoute && request.method === 'POST' && !certificatesRoute[1]) { if (!protect(request, response)) return; const person = facilitators.getFacilitator(Number(certificatesRoute[0])); if (!person) return json(response, 404, { message: 'Fasilitator tidak ditemukan.' }); const parts = await readMultipart(request); const urlValue = saveUpload(parts.file, 'certificate'); const data = facilitators.createCertificate(Number(certificatesRoute[0]), { name: parts.name, notes: parts.notes, url: urlValue }); return json(response, 201, { data }) }
    if (certificatesRoute && request.method === 'DELETE' && certificatesRoute[1]) { if (!protect(request, response)) return; const data = facilitators.deleteCertificate(Number(certificatesRoute[0]), Number(certificatesRoute[1])); return data ? json(response, 200, { data }) : json(response, 404, { message: 'Sertifikat tidak ditemukan.' }) }
    const profileId = route(url, /^\/api\/facilitators\/(\d+)\/competency-profile$/)
    if (request.method === 'GET' && profileId) { const data = facilitators.competencyProfile(Number(profileId[0])); return data ? json(response, 200, data) : json(response, 404, { message: 'Fasilitator tidak ditemukan.' }) }
    const reviewId = route(url, /^\/api\/facilitators\/(\d+)\/reviews$/)
    if (request.method === 'POST' && reviewId) { if (!protect(request, response)) return; const input = await readJson(request); input.authorName ||= access(request)?.name || 'Admin'; input.comment ||= 'Rating kegiatan'; const errors = validateReview(input); if (Object.keys(errors).length) return invalid(response, errors); const review = facilitators.createReview(Number(reviewId[0]), input); return review ? json(response, 201, { data: review }) : json(response, 404, { message: 'Fasilitator tidak ditemukan.' }) }
    const trainingReviewId = route(url, /^\/api\/facilitators\/(\d+)\/trainings\/(\d+)\/(review|rating)$/)
    if (request.method === 'POST' && trainingReviewId) { if (!protect(request, response)) return; const input = await readJson(request); input.authorName ||= access(request)?.name || 'Admin'; input.comment ||= 'Rating kegiatan'; const errors = validateReview(input); if (Object.keys(errors).length) return invalid(response, errors); return json(response, 201, { data: facilitators.createTrainingReview(Number(trainingReviewId[0]), Number(trainingReviewId[1]), input) }) }
    const trainingCertificateRoute = route(url, /^\/api\/facilitators\/(\d+)\/trainings\/(\d+)\/certificate$/)
    if (trainingCertificateRoute && request.method === 'POST') { if (!protect(request, response)) return; const parts = await readMultipart(request); const urlValue = saveUpload(parts.file, 'certificate'); const data = facilitators.attachTrainingCertificate(Number(trainingCertificateRoute[0]), Number(trainingCertificateRoute[1]), urlValue); return data ? json(response, 200, { data }) : json(response, 404, { message: 'Pelatihan tidak ditemukan.' }) }
    const trainingRoute = route(url, /^\/api\/facilitators\/(\d+)\/trainings(?:\/(\d+))?$/)
    if (trainingRoute && request.method === 'GET' && !trainingRoute[1]) return json(response, 200, { data: facilitators.listTrainings(Number(trainingRoute[0])) })
    if (trainingRoute && ['POST', 'PUT'].includes(request.method)) { if (!protect(request, response)) return; const input = await readJson(request); const errors = validateTraining(input); if (Object.keys(errors).length) return invalid(response, errors); const data = request.method === 'POST' ? facilitators.createTraining(Number(trainingRoute[0]), input) : facilitators.updateTraining(Number(trainingRoute[0]), Number(trainingRoute[1]), input); return data ? json(response, request.method === 'POST' ? 201 : 200, { data }) : json(response, 404, { message: 'Fasilitator atau riwayat tidak ditemukan.' }) }
    if (trainingRoute && request.method === 'DELETE' && trainingRoute[1]) { if (!protect(request, response)) return; const data = facilitators.deleteTraining(Number(trainingRoute[0]), Number(trainingRoute[1])); return data ? json(response, 200, { data }) : json(response, 404, { message: 'Riwayat tidak ditemukan.' }) }
    const educationRoute = route(url, /^\/api\/facilitators\/(\d+)\/educations(?:\/(\d+))?$/)
    if (educationRoute && request.method === 'GET' && !educationRoute[1]) return json(response, 200, { data: facilitators.listEducations(Number(educationRoute[0])) })
    if (educationRoute && ['POST', 'PUT'].includes(request.method)) { if (!protect(request, response)) return; const input = await readJson(request); const errors = validateEducation(input); if (Object.keys(errors).length) return invalid(response, errors); const data = request.method === 'POST' ? facilitators.createEducation(Number(educationRoute[0]), input) : facilitators.updateEducation(Number(educationRoute[0]), Number(educationRoute[1]), input); return data ? json(response, request.method === 'POST' ? 201 : 200, { data }) : json(response, 404, { message: 'Fasilitator atau riwayat pendidikan tidak ditemukan.' }) }
    if (educationRoute && request.method === 'DELETE' && educationRoute[1]) { if (!protect(request, response)) return; const data = facilitators.deleteEducation(Number(educationRoute[0]), Number(educationRoute[1])); return data ? json(response, 200, { data }) : json(response, 404, { message: 'Riwayat pendidikan tidak ditemukan.' }) }
    if (request.method === 'POST' && url.pathname === '/api/facilitators') { if (!protect(request, response)) return; const input = await readJson(request); const errors = validateFacilitator(input); if (Object.keys(errors).length) return invalid(response, errors); return json(response, 201, { data: facilitators.createFacilitator(input) }) }
    const facilitatorId = route(url, /^\/api\/facilitators\/(\d+)$/)
    if (request.method === 'GET' && facilitatorId) { const data = facilitators.getFacilitator(Number(facilitatorId[0])); return data ? json(response, 200, { data }) : json(response, 404, { message: 'Fasilitator tidak ditemukan.' }) }
    if (request.method === 'PUT' && facilitatorId) { if (!protect(request, response)) return; const input = await readJson(request); const errors = validateFacilitator({ ...input, name: input.name || 'existing' }); if (Object.keys(errors).length) return invalid(response, errors); const data = facilitators.updateFacilitator(Number(facilitatorId[0]), input); return data ? json(response, 200, { data }) : json(response, 404, { message: 'Fasilitator tidak ditemukan.' }) }
    if (request.method === 'DELETE' && facilitatorId) { if (!protect(request, response)) return; const data = facilitators.deleteFacilitator(Number(facilitatorId[0])); return data ? json(response, 200, { data }) : json(response, 404, { message: 'Fasilitator tidak ditemukan.' }) }
    if (request.method === 'GET' && url.pathname.startsWith('/uploads/')) { const requestedName = decodeURIComponent(url.pathname.slice('/uploads/'.length)); const file = normalizePath(resolve(uploadDirectory, requestedName)); const relativeFile = relative(uploadDirectory, file); if (!relativeFile || relativeFile.startsWith('..') || relativeFile.includes(`..${'\\'}`) || !existsSync(file)) return json(response, 404, { message: 'File tidak ditemukan.' }); const contentTypes = { '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg', '.png': 'image/png', '.webp': 'image/webp', '.pdf': 'application/pdf' }; const origin = request.headers.origin; const allowedOrigins = ['http://localhost:5173', 'http://127.0.0.1:5173', process.env.WEB_ORIGIN].filter(Boolean); const headers = { 'Content-Type': contentTypes[extname(file).toLowerCase()] || 'application/octet-stream', 'Cache-Control': 'public, max-age=3600' }; if (allowedOrigins.includes(origin)) { headers['Access-Control-Allow-Origin'] = origin; headers.Vary = 'Origin' } response.writeHead(200, headers); return response.end(readFileSync(file)) }
    return json(response, 404, { message: 'Endpoint tidak ditemukan.' })
  } catch (error) { console.error(error); return json(response, error.status || 500, { message: error.message || 'Terjadi kesalahan server.' }) }
})
server.listen(port, () => console.log(`API UPELKES berjalan di http://localhost:${port}`))
