import { db, transaction } from '../database/database.js'

const fields = ['name', 'degree', 'birthInfo', 'nik', 'nip', 'position', 'unit', 'address', 'phone', 'email', 'photoUrl', 'signatureUrl', 'status']
const columns = { birthInfo: 'birth_info', photoUrl: 'photo_url', signatureUrl: 'signature_url' }
const normalize = (person) => person && ({ ...person, birthInfo: person.birth_info, photoUrl: person.photo_url, signatureUrl: person.signature_url, birth_info: undefined, photo_url: undefined, signature_url: undefined })
function replaceList(table, facilitatorId, values, field = 'name') { db.prepare(`DELETE FROM ${table} WHERE facilitator_id = ?`).run(facilitatorId); const insert = db.prepare(`INSERT INTO ${table} (facilitator_id, ${field}) VALUES (?, ?)`); for (const value of values || []) insert.run(facilitatorId, typeof value === 'string' ? value.trim() : value[field]) }
function savePerson(id, input) { const allowed = fields.filter((field) => input[field] !== undefined); if (allowed.length) { const update = allowed.map((field) => `${columns[field] || field.replace(/[A-Z]/g, (letter) => `_${letter.toLowerCase()}`)} = ?`).join(', '); db.prepare(`UPDATE facilitators SET ${update}, updated_at = CURRENT_TIMESTAMP WHERE id = ?`).run(...allowed.map((field) => input[field]), id) } if (input.competencies) replaceList('facilitator_competencies', id, input.competencies); return getFacilitator(id) }
export function createFacilitator(input) { return transaction(() => { const person = db.prepare('INSERT INTO facilitators (name, degree, birth_info, nik, nip, position, unit, address, phone, email, photo_url, signature_url, status) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)').run(input.name.trim(), input.degree || null, input.birthInfo || null, input.nik || null, input.nip || null, input.position || null, input.unit || null, input.address || null, input.phone || null, input.email || null, input.photoUrl || null, input.signatureUrl || null, input.status || 'active'); return savePerson(Number(person.lastInsertRowid), input) }) }
export function updateFacilitator(id, input) { if (!getFacilitator(id)) return null; return transaction(() => savePerson(id, input)) }
export function getFacilitator(id) { const person = normalize(db.prepare('SELECT * FROM facilitators WHERE id = ?').get(id)); if (!person) return null; person.competencies = db.prepare('SELECT name FROM facilitator_competencies WHERE facilitator_id = ? ORDER BY name').all(id).map((item) => item.name); return person }
export function listFacilitators() { return db.prepare('SELECT id FROM facilitators ORDER BY name').all().map(({ id }) => getFacilitator(id)) }
export function deleteFacilitator(id) { if (!getFacilitator(id)) return null; transaction(() => db.prepare('DELETE FROM facilitators WHERE id = ?').run(id)); return { id: Number(id) } }
export function monitoring(filter = '') { let clause = ''; const exists = (expression) => `EXISTS (SELECT 1 FROM facilitator_competencies c WHERE c.facilitator_id = f.id ${expression})`; if (filter === 'missing_photo') clause = 'WHERE f.photo_url IS NULL OR f.photo_url = \'\''; if (filter === 'missing_signature') clause = 'WHERE f.signature_url IS NULL OR f.signature_url = \'\''; if (filter === 'missing_certificate') clause = "WHERE NOT EXISTS (SELECT 1 FROM facilitator_documents d WHERE d.facilitator_id = f.id AND d.type = 'certificate')"; if (filter === 'missing_material') clause = `WHERE NOT ${exists('')}`; if (filter === 'incomplete') clause = "WHERE f.photo_url IS NULL OR f.signature_url IS NULL OR NOT EXISTS (SELECT 1 FROM facilitator_documents d WHERE d.facilitator_id = f.id AND d.type = 'certificate') OR NOT EXISTS (SELECT 1 FROM facilitator_competencies c WHERE c.facilitator_id = f.id) OR NOT EXISTS (SELECT 1 FROM facilitator_educations e WHERE e.facilitator_id = f.id) OR NOT EXISTS (SELECT 1 FROM facilitator_documents d WHERE d.facilitator_id = f.id AND d.type = 'supporting')"; const rows = db.prepare(`SELECT f.id, f.name, f.position, f.photo_url, f.signature_url, EXISTS (SELECT 1 FROM facilitator_documents d WHERE d.facilitator_id = f.id AND d.type = 'certificate') has_certificate, ${exists('')} has_material, EXISTS (SELECT 1 FROM facilitator_educations e WHERE e.facilitator_id = f.id) has_education, EXISTS (SELECT 1 FROM facilitator_documents d WHERE d.facilitator_id = f.id AND d.type = 'supporting') has_supporting FROM facilitators f ${clause} ORDER BY f.name`).all(); return rows.map((row) => ({ id: row.id, name: row.name, position: row.position, requirements: [{ key: 'photo', label: 'Foto', isComplete: Boolean(row.photo_url) }, { key: 'signature', label: 'TTD', isComplete: Boolean(row.signature_url) }, { key: 'certificate', label: 'Sertifikat', isComplete: Boolean(row.has_certificate) }, { key: 'material', label: 'Materi', isComplete: Boolean(row.has_material) }, { key: 'education', label: 'Riwayat Pendidikan', isComplete: Boolean(row.has_education) }, { key: 'supporting', label: 'Dokumen Pendukung', isComplete: Boolean(row.has_supporting) }] })) }
export function search(filters) { const conditions = []; const params = []; if (filters.query) { conditions.push('LOWER(f.name) LIKE ?'); params.push(`%${filters.query.toLowerCase()}%`) } if (filters.competency) { conditions.push('EXISTS (SELECT 1 FROM facilitator_competencies c WHERE c.facilitator_id = f.id AND LOWER(c.name) LIKE ?)'); params.push(`%${filters.competency.toLowerCase()}%`) } if (filters.status) { conditions.push('f.status = ?'); params.push(filters.status) } if (filters.min_rating) { conditions.push('COALESCE((SELECT AVG(rating) FROM reviews r WHERE r.facilitator_id = f.id), 0) >= ?'); params.push(Number(filters.min_rating)) } const where = conditions.length ? `WHERE ${conditions.join(' AND ')}` : ''; const rows = db.prepare(`SELECT f.id, f.name, f.photo_url, f.status, ROUND(COALESCE((SELECT AVG(r.rating) FROM reviews r WHERE r.facilitator_id = f.id), 0), 1) average_rating, (SELECT COUNT(*) FROM reviews r WHERE r.facilitator_id = f.id) rating_count, (SELECT COUNT(*) FROM trainings t WHERE t.facilitator_id = f.id) training_count FROM facilitators f ${where} ORDER BY f.name LIMIT 50`).all(...params); return rows.map((row) => ({ id: row.id, name: row.name, photoUrl: row.photo_url, status: row.status, statusLabel: row.status === 'active' ? 'Aktif' : 'Tidak aktif', averageRating: row.average_rating || null, ratingCount: row.rating_count, trainingCount: row.training_count, competencies: db.prepare('SELECT name FROM facilitator_competencies WHERE facilitator_id = ? ORDER BY name').all(row.id).map((item) => item.name) })) }
export function competencyProfile(id) { const person = getFacilitator(id); if (!person) return null; const rating = db.prepare('SELECT ROUND(AVG(rating), 1) average, COUNT(*) count FROM reviews WHERE facilitator_id = ?').get(id); const documentRows = db.prepare('SELECT type, url FROM facilitator_documents WHERE facilitator_id = ? ORDER BY created_at DESC').all(id); const documents = { Foto: person.photoUrl, TTD: person.signatureUrl, CV: documentRows.find((item) => item.type === 'cv')?.url, Sertifikat: documentRows.find((item) => item.type === 'certificate')?.url }; return { ...person, rating: { average: rating.average, count: rating.count }, documents, trainings: db.prepare('SELECT id, name, material, event_date date, organizer FROM trainings WHERE facilitator_id = ? ORDER BY event_date DESC').all(id), reviews: db.prepare('SELECT id, author_name authorName, rating, comment, created_at createdAt FROM reviews WHERE facilitator_id = ? ORDER BY created_at DESC').all(id) } }
export function createReview(id, input) { if (!getFacilitator(id)) return null; return transaction(() => { const result = db.prepare('INSERT INTO reviews (facilitator_id, author_name, rating, comment) VALUES (?, ?, ?, ?)').run(id, input.authorName.trim(), input.rating, input.comment.trim()); return db.prepare('SELECT id, author_name authorName, rating, comment, created_at createdAt FROM reviews WHERE id = ?').get(result.lastInsertRowid) }) }
