import { db, transaction } from '../database/database.js'

const fields = ['name', 'degree', 'birthInfo', 'nik', 'nip', 'rank', 'position', 'unit', 'officeAddress', 'homeAddress', 'phone', 'email', 'photoUrl', 'signatureUrl', 'status']
const columns = { birthInfo: 'birth_info', photoUrl: 'photo_url', signatureUrl: 'signature_url' }
const columnsWithAliases = { ...columns, officeAddress: 'office_address', homeAddress: 'home_address' }
const completenessLabels = { name: 'Nama lengkap', degree: 'Gelar', birthInfo: 'Tempat/tanggal lahir', nik: 'NIK', nip: 'NIP', rank: 'Pangkat/golongan', position: 'Jabatan', unit: 'Unit kerja', officeAddress: 'Alamat kantor', homeAddress: 'Alamat rumah', phone: 'No. HP', email: 'Email', photo: 'Foto', signature: 'TTD', competencies: 'Pelatihan dan materi yang dikuasai', relatedTraining: 'Pendidikan/pelatihan terkait materi', teachingExperience: 'Pengalaman melatih/mengajar', certificate: 'Sertifikat pelatihan', material: 'Materi pelatihan', education: 'Riwayat pendidikan', supporting: 'Dokumen pendukung' }
const normalize = (person) => person && ({ ...person, birthInfo: person.birth_info, photoUrl: person.photo_url, signatureUrl: person.signature_url, officeAddress: person.office_address, homeAddress: person.home_address, birth_info: undefined, photo_url: undefined, signature_url: undefined, office_address: undefined, home_address: undefined, address: undefined })
function getRatingSummary(id) {
  return db.prepare("SELECT ROUND(AVG(score), 1) average, COUNT(*) count FROM (SELECT r.rating score FROM reviews r WHERE r.facilitator_id = ? UNION ALL SELECT t.rating score FROM trainings t WHERE t.facilitator_id = ? AND t.rating IS NOT NULL AND NOT EXISTS (SELECT 1 FROM reviews r WHERE r.training_id = t.id))").get(id, id)
}
function replaceCompetencies(facilitatorId, values, trainingNames = []) { if (!db.prepare('SELECT id FROM facilitators WHERE id = ?').get(facilitatorId)) throw new Error(`Fasilitator ${facilitatorId} tidak ditemukan saat menyimpan kompetensi.`); db.prepare('DELETE FROM facilitator_competencies WHERE facilitator_id = ?').run(facilitatorId); const insert = db.prepare('INSERT INTO facilitator_competencies (facilitator_id, name, started_teaching_year, training_name) VALUES (?, ?, ?, ?)'); const catalogInsert = db.prepare('INSERT OR IGNORE INTO training_subject_catalog (name) VALUES (?)'); for (const value of values || []) { const item = typeof value === 'string' ? { name: value } : value; const name = item.name?.trim(); if (!name) continue; const trainingName = (item.trainingName ?? item.training ?? item.training_name)?.trim() || null; insert.run(facilitatorId, name, item.startedTeachingYear ?? null, trainingName); catalogInsert.run(name) } for (const value of trainingNames || []) { const name = value?.trim(); if (name) catalogInsert.run(name) } }
function savePerson(id, input) { const allowed = fields.filter((field) => input[field] !== undefined); if (allowed.length) { const update = allowed.map((field) => `${columnsWithAliases[field] || field.replace(/[A-Z]/g, (letter) => `_${letter.toLowerCase()}`)} = ?`).join(', '); db.prepare(`UPDATE facilitators SET ${update}, updated_at = CURRENT_TIMESTAMP WHERE id = ?`).run(...allowed.map((field) => input[field]), id) } if (input.competencies) replaceCompetencies(id, input.competencies, input.trainingNames); return getFacilitator(id) }
export function createFacilitator(input) { return transaction(() => { db.prepare('INSERT INTO facilitators (name, degree, birth_info, nik, nip, rank, position, unit, office_address, home_address, phone, email, photo_url, signature_url, status) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)').run(input.name.trim(), input.degree || null, input.birthInfo || null, input.nik || null, input.nip || null, input.rank || null, input.position || null, input.unit || null, input.officeAddress || null, input.homeAddress || null, input.phone || null, input.email || null, input.photoUrl || null, input.signatureUrl || null, input.status || 'active'); const id = db.prepare('SELECT id FROM facilitators WHERE rowid = last_insert_rowid()').get().id; return savePerson(Number(id), input) }) }
export function updateFacilitator(id, input) { if (!getFacilitator(id)) return null; return transaction(() => savePerson(id, input)) }
export function getFacilitator(id) {
  const person = normalize(db.prepare('SELECT * FROM facilitators WHERE id = ?').get(id))
  if (!person) return null
  person.competencies = db.prepare('SELECT name, started_teaching_year startedTeachingYear, training_name trainingName FROM facilitator_competencies WHERE facilitator_id = ? ORDER BY training_name, name').all(id)
  person.trainingNames = db.prepare("SELECT DISTINCT training_name name FROM facilitator_competencies WHERE facilitator_id = ? AND TRIM(COALESCE(training_name, '')) <> ''").all(id).map((item) => item.name)
  person.supportingDocuments = db.prepare("SELECT id, name, url, notes, created_at createdAt FROM facilitator_documents WHERE facilitator_id = ? AND type = 'supporting' ORDER BY created_at DESC").all(id)
  const hasRelatedTraining = Boolean(db.prepare("SELECT 1 FROM trainings WHERE facilitator_id = ? AND category = 'related_training' LIMIT 1").get(id))
  const hasTeachingExperience = Boolean(db.prepare("SELECT 1 FROM trainings WHERE facilitator_id = ? AND category = 'teaching_experience' LIMIT 1").get(id))
  const checks = {
    name: Boolean(person.name?.trim()),
    degree: Boolean(person.degree?.trim()),
    birthInfo: Boolean(person.birthInfo?.trim()),
    nik: Boolean(person.nik?.trim()),
    nip: Boolean(person.nip?.trim()),
    rank: Boolean(person.rank?.trim()),
    position: Boolean(person.position?.trim()),
    unit: Boolean(person.unit?.trim()),
    officeAddress: Boolean(person.officeAddress?.trim()),
    homeAddress: Boolean(person.homeAddress?.trim()),
    phone: Boolean(person.phone?.trim()),
    email: Boolean(person.email?.trim()),
    photo: Boolean(person.photoUrl),
    signature: Boolean(person.signatureUrl),
    competencies: Boolean(person.competencies.length || person.trainingNames.length),
    relatedTraining: hasRelatedTraining,
    teachingExperience: hasTeachingExperience,
    certificate: Boolean(db.prepare("SELECT 1 FROM trainings WHERE facilitator_id = ? AND category = 'related_training' AND TRIM(COALESCE(certificate_url, '')) <> '' LIMIT 1").get(id)),
    material: Boolean(db.prepare("SELECT 1 FROM trainings WHERE facilitator_id = ? AND TRIM(COALESCE(material, '')) <> '' LIMIT 1").get(id)),
    education: Boolean(db.prepare('SELECT 1 FROM facilitator_educations WHERE facilitator_id = ? LIMIT 1').get(id)),
    supporting: Boolean(db.prepare("SELECT 1 FROM facilitator_documents WHERE facilitator_id = ? AND type = 'supporting' LIMIT 1").get(id)),
  }
  const rating = getRatingSummary(id)
  person.completeness = { isComplete: Object.values(checks).every(Boolean), checks }
  person.rating = { average: rating.average, count: rating.count }
  return person
}
export function createSupportingDocument(id, input) { if (!getFacilitator(id)) return null; const result = db.prepare("INSERT INTO facilitator_documents (facilitator_id, type, name, url, notes) VALUES (?, 'supporting', ?, ?, ?)").run(id, input.name?.trim() || 'Dokumen Pendukung', input.url, input.notes?.trim() || null); return db.prepare("SELECT id, name, url, notes, created_at createdAt FROM facilitator_documents WHERE id = ?").get(result.lastInsertRowid) }
export function listFacilitators() { return db.prepare('SELECT id FROM facilitators ORDER BY name').all().map(({ id }) => getFacilitator(id)) }
export function deleteFacilitator(id) { if (!getFacilitator(id)) return null; transaction(() => db.prepare('DELETE FROM facilitators WHERE id = ?').run(id)); return { id: Number(id) } }
export function monitoring(filter = '') {
  let clause = ''
  const hasMaterial = "EXISTS (SELECT 1 FROM trainings t WHERE t.facilitator_id = f.id AND TRIM(COALESCE(t.material, '')) <> '')"
  if (filter === 'missing_photo') clause = "WHERE f.photo_url IS NULL OR f.photo_url = ''"
  if (filter === 'missing_signature') clause = "WHERE f.signature_url IS NULL OR f.signature_url = ''"
  if (filter === 'missing_certificate') clause = "WHERE NOT EXISTS (SELECT 1 FROM facilitator_documents d WHERE d.facilitator_id = f.id AND d.type = 'certificate')"
  if (filter === 'missing_material') clause = `WHERE NOT ${hasMaterial}`
  if (filter === 'incomplete') clause = ''
  const rows = db.prepare(`SELECT f.id, f.name, f.position, f.nik, f.unit, f.phone, f.email, f.photo_url, f.signature_url, EXISTS (SELECT 1 FROM facilitator_documents d WHERE d.facilitator_id = f.id AND d.type = 'certificate') has_certificate, ${hasMaterial} has_material, EXISTS (SELECT 1 FROM facilitator_educations e WHERE e.facilitator_id = f.id) has_education, EXISTS (SELECT 1 FROM facilitator_documents d WHERE d.facilitator_id = f.id AND d.type = 'supporting') has_supporting FROM facilitators f ${clause} ORDER BY f.name`).all()
  const visibleRows = filter === 'incomplete' ? rows.filter((row) => !getFacilitator(row.id)?.completeness?.isComplete) : rows
  return visibleRows.map((row) => ({ id: row.id, name: row.name, position: row.position, photoUrl: row.photo_url, requirements: Object.entries(getFacilitator(row.id)?.completeness?.checks || {}).map(([key, isComplete]) => ({ key, label: completenessLabels[key] || key, isComplete })) }))
}
export function search(filters) { const conditions = []; const params = []; if (filters.query) { conditions.push('LOWER(f.name) LIKE ?'); params.push(`%${filters.query.toLowerCase()}%`) } if (filters.competency) { conditions.push('EXISTS (SELECT 1 FROM facilitator_competencies c WHERE c.facilitator_id = f.id AND LOWER(c.name) LIKE ?)'); params.push(`%${filters.competency.toLowerCase()}%`) } if (filters.status) { conditions.push('f.status = ?'); params.push(filters.status) } if (filters.min_rating) { conditions.push("COALESCE((SELECT AVG(score) FROM (SELECT r.rating score FROM reviews r WHERE r.facilitator_id = f.id UNION ALL SELECT t.rating score FROM trainings t WHERE t.facilitator_id = f.id AND t.rating IS NOT NULL AND NOT EXISTS (SELECT 1 FROM reviews r2 WHERE r2.training_id = t.id))), 0) >= ?"); params.push(Number(filters.min_rating)) } const where = conditions.length ? `WHERE ${conditions.join(' AND ')}` : ''; const rows = db.prepare(`SELECT f.id, f.name, f.photo_url, f.status, (SELECT COUNT(*) FROM trainings t WHERE t.facilitator_id = f.id) training_count FROM facilitators f ${where} ORDER BY f.name LIMIT 50`).all(...params); return rows.map((row) => { const rating = getRatingSummary(row.id); return { id: row.id, name: row.name, photoUrl: row.photo_url, status: row.status, statusLabel: row.status === 'active' ? 'Aktif' : 'Tidak aktif', averageRating: rating.average || null, ratingCount: rating.count, trainingCount: row.training_count, competencies: db.prepare('SELECT name, started_teaching_year startedTeachingYear FROM facilitator_competencies WHERE facilitator_id = ? ORDER BY name').all(row.id) } }) }
export function dashboardSummary() {
  const now = new Date()
  const today = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')}`
  const monthStart = `${today.slice(0, 7)}-01`
  const total = db.prepare('SELECT COUNT(*) count FROM facilitators').get().count
  const completeCondition = `f.photo_url IS NOT NULL AND f.photo_url <> '' AND f.signature_url IS NOT NULL AND f.signature_url <> '' AND EXISTS (SELECT 1 FROM trainings t WHERE t.facilitator_id = f.id AND t.category = 'related_training' AND TRIM(COALESCE(t.certificate_url, '')) <> '') AND EXISTS (SELECT 1 FROM trainings t WHERE t.facilitator_id = f.id AND TRIM(COALESCE(t.material, '')) <> '') AND EXISTS (SELECT 1 FROM facilitator_educations e WHERE e.facilitator_id = f.id) AND EXISTS (SELECT 1 FROM facilitator_documents d WHERE d.facilitator_id = f.id AND d.type = 'supporting')`
  const count = (sql, ...params) => db.prepare(sql).get(...params).count
  const complete = listFacilitators().filter((person) => person.completeness?.isComplete).length
  const activities = count('SELECT COUNT(*) count FROM trainings WHERE is_catalog_only = 0')
  const thisMonth = count("SELECT COUNT(*) count FROM trainings WHERE is_catalog_only = 0 AND event_date >= ? AND event_date < date(?, '+1 month')", monthStart, monthStart)
  const pendingRatings = count("SELECT COUNT(*) count FROM trainings WHERE is_catalog_only = 0 AND COALESCE(end_date, event_date) < ? AND rating IS NULL AND NOT EXISTS (SELECT 1 FROM reviews r WHERE r.training_id = trainings.id)", today)
  const pendingRatingActivities = db.prepare("SELECT t.id, t.name, COALESCE(t.start_date, t.event_date) startDate, COALESCE(t.end_date, t.event_date) endDate, f.name facilitator FROM trainings t JOIN facilitators f ON f.id = t.facilitator_id WHERE t.is_catalog_only = 0 AND COALESCE(t.end_date, t.event_date) < ? AND t.rating IS NULL AND NOT EXISTS (SELECT 1 FROM reviews r WHERE r.training_id = t.id) ORDER BY COALESCE(t.end_date, t.event_date) DESC LIMIT 5").all(today)
  const newSubmissions = count('SELECT COUNT(*) count FROM facilitators WHERE created_at >= ?', monthStart)
  const missing = {
    photo: count("SELECT COUNT(*) count FROM facilitators WHERE photo_url IS NULL OR photo_url = ''"),
    signature: count("SELECT COUNT(*) count FROM facilitators WHERE signature_url IS NULL OR signature_url = ''"),
    certificate: count("SELECT COUNT(*) count FROM facilitators f WHERE NOT EXISTS (SELECT 1 FROM trainings t WHERE t.facilitator_id = f.id AND t.category = 'related_training' AND TRIM(COALESCE(t.certificate_url, '')) <> '')"),
    materials: count("SELECT COUNT(*) count FROM facilitators f WHERE NOT EXISTS (SELECT 1 FROM trainings t WHERE t.facilitator_id = f.id AND TRIM(COALESCE(t.material, '')) <> '')"),
  }
  const upcoming = db.prepare(`SELECT t.id, t.name, t.material, COALESCE(t.start_date, t.event_date) date, COALESCE(t.start_date, t.event_date) startDate, COALESCE(t.end_date, t.event_date) endDate, t.color, t.role, t.organizer, f.name facilitator, t.category FROM trainings t JOIN facilitators f ON f.id = t.facilitator_id WHERE t.is_catalog_only = 0 AND COALESCE(t.end_date, t.event_date) >= ? ORDER BY COALESCE(t.start_date, t.event_date) ASC LIMIT 5`).all(today)
  const allActivities = db.prepare("SELECT t.id, t.facilitator_id facilitatorId, t.name, t.material, t.organizer, t.participant_count participantCount, t.rating, COALESCE(t.start_date, t.event_date) startDate, COALESCE(t.end_date, t.event_date) endDate, t.color, f.name facilitator, f.degree facilitatorDegree, f.photo_url facilitatorPhotoUrl, f.phone facilitatorPhone, f.email facilitatorEmail, ROUND(COALESCE((SELECT AVG(score) FROM (SELECT r.rating score FROM reviews r WHERE r.facilitator_id = f.id UNION ALL SELECT t2.rating score FROM trainings t2 WHERE t2.facilitator_id = f.id AND t2.rating IS NOT NULL AND NOT EXISTS (SELECT 1 FROM reviews r2 WHERE r2.training_id = t2.id))), 0), 1) facilitatorRating, (SELECT COUNT(*) FROM reviews r WHERE r.training_id = t.id) reviewCount FROM trainings t JOIN facilitators f ON f.id = t.facilitator_id WHERE t.is_catalog_only = 0 ORDER BY COALESCE(t.start_date, t.event_date) DESC, t.id DESC").all()
  const facilitatorSummary = listFacilitators().map((person) => ({
    id: person.id,
    name: person.name,
    degree: person.degree,
    position: person.position,
    createdAt: person.created_at || person.createdAt,
    averageRating: person.rating?.average,
    isComplete: person.completeness.isComplete,
    completeness: person.completeness,
  }))
  const calendarActivities = db.prepare("SELECT id, name, COALESCE(start_date, event_date) startDate, COALESCE(end_date, event_date) endDate, color FROM trainings WHERE is_catalog_only = 0 AND COALESCE(end_date, event_date) >= ? AND COALESCE(start_date, event_date) < date(?, '+1 month') ORDER BY COALESCE(start_date, event_date)").all(monthStart, monthStart)
  return { stats: [
    { key: 'facilitators', label: 'Total Fasilitator', value: total, tone: 'purple' },
    { key: 'complete', label: 'Data Lengkap', value: complete, tone: 'green' },
    { key: 'incomplete', label: 'Data Belum Lengkap', value: total - complete, tone: 'orange' },
    { key: 'activities', label: 'Total Pelatihan / Kegiatan', value: activities, tone: 'blue' },
    { key: 'thisMonth', label: 'Kegiatan Bulan Ini', value: thisMonth, tone: 'cyan' },
    { key: 'pendingRatings', label: 'Agenda Belum Dirating', value: pendingRatings, tone: 'pink' },
  ], upcomingActivities: upcoming, allActivities, facilitatorSummary, calendarActivities, monitoring: [
    { key: 'photo', label: 'Belum memiliki foto', value: missing.photo },
    { key: 'signature', label: 'Belum memiliki TTD', value: missing.signature },
    { key: 'certificate', label: 'Belum memiliki sertifikat', value: missing.certificate },
    { key: 'materials', label: 'Belum memiliki materi', value: missing.materials },
  ], notifications: { upcoming, upcomingCount: upcoming.length, pendingRatings, pendingRatingActivities, newSubmissions, incompleteCount: total - complete } }
}
const certificateSelect = 'SELECT id, name, url, notes, created_at createdAt FROM facilitator_documents WHERE facilitator_id = ? AND type = \'certificate\''
export function listCertificates(id) { if (!getFacilitator(id)) return null; return db.prepare(`${certificateSelect} ORDER BY created_at DESC, id DESC`).all(id) }
export function createCertificate(id, input) { if (!getFacilitator(id)) return null; const name = input.name?.trim() || 'Sertifikat'; const result = db.prepare("INSERT INTO facilitator_documents (facilitator_id, type, name, url, notes) VALUES (?, 'certificate', ?, ?, ?)").run(id, name, input.url, input.notes?.trim() || null); return db.prepare(`${certificateSelect} AND id = ?`).get(id, result.lastInsertRowid) }
export function deleteCertificate(id, certificateId) { const result = db.prepare("DELETE FROM facilitator_documents WHERE id = ? AND facilitator_id = ? AND type = 'certificate'").run(certificateId, id); return result.changes ? { id: Number(certificateId) } : null }
export function competencyProfile(id) { const person = getFacilitator(id); if (!person) return null; const rating = getRatingSummary(id); const documentRows = db.prepare('SELECT type, url FROM facilitator_documents WHERE facilitator_id = ? ORDER BY created_at DESC').all(id); const documents = { Foto: person.photoUrl, TTD: person.signatureUrl, CV: documentRows.find((item) => item.type === 'cv')?.url, Sertifikat: documentRows.find((item) => item.type === 'certificate')?.url }; return { ...person, rating: { average: rating.average, count: rating.count }, documents, certificates: listCertificates(id), educations: listEducations(id), trainings: listTrainings(id), reviews: db.prepare('SELECT id, author_name authorName, rating, comment, created_at createdAt FROM reviews WHERE facilitator_id = ? ORDER BY created_at DESC').all(id) } }
const trainingSelect = "SELECT id, name, material, material subject, event_date date, COALESCE(start_date, event_date) startDate, COALESCE(end_date, event_date) endDate, color, organizer, role, category, participant_count participantCount, rating, certificate_url certificateUrl, notes, is_catalog_only catalogOnly, (SELECT COUNT(*) FROM reviews r WHERE r.training_id = trainings.id) reviewCount FROM trainings"
function trainingMaterial(input) { return (input.material ?? input.subject)?.trim() || null }
function syncCompetency(id, material) { const name = material?.trim(); if (name) { db.prepare('INSERT OR IGNORE INTO facilitator_competencies (facilitator_id, name) VALUES (?, ?)').run(id, name); db.prepare('INSERT OR IGNORE INTO training_subject_catalog (name) VALUES (?)').run(name) } }
export function listTrainingSubjects() { return db.prepare('SELECT name FROM training_subject_catalog ORDER BY name').all().map((item) => item.name) }
export function listTrainingCatalog() { const rows = db.prepare("SELECT name, material FROM trainings WHERE TRIM(COALESCE(name, '')) <> '' GROUP BY name, material UNION SELECT training_name name, name material FROM facilitator_competencies WHERE TRIM(COALESCE(training_name, '')) <> '' GROUP BY training_name, name ORDER BY name, material").all(); return rows.reduce((catalog, row) => { let item = catalog.find((entry) => entry.name.toLowerCase() === row.name.toLowerCase()); if (!item) { item = { name: row.name, materials: [] }; catalog.push(item) } if (row.material?.trim() && !item.materials.some((material) => material.toLowerCase() === row.material.toLowerCase())) item.materials.push(row.material); return catalog }, []) }
export function createTrainingSubject(name) { const value = name?.trim(); if (!value) throw Object.assign(new Error('Nama bidang pelatihan wajib diisi.'), { status: 422 }); db.prepare('INSERT OR IGNORE INTO training_subject_catalog (name) VALUES (?)').run(value); return db.prepare('SELECT name FROM training_subject_catalog WHERE name = ?').get(value).name }
export function listTrainings(id) { return db.prepare(`${trainingSelect} WHERE facilitator_id = ? ORDER BY event_date DESC`).all(id) }
export function createTraining(id, input) { if (!getFacilitator(id)) return null; const startDate = input.startDate || input.date; const endDate = input.endDate || startDate; const material = trainingMaterial(input); const result = db.prepare('INSERT INTO trainings (facilitator_id, name, material, event_date, start_date, end_date, color, organizer, role, category, participant_count, rating, certificate_url, notes, is_catalog_only) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)').run(id, input.name.trim(), material, startDate, startDate, endDate, input.color || '#9f58cc', input.organizer || null, input.role || null, input.category || 'teaching_experience', input.participantCount ?? null, input.rating == null || input.rating === '' ? null : Number(input.rating), input.certificateUrl || null, input.notes || null, input.catalogOnly ? 1 : 0); syncCompetency(id, material); return db.prepare(`${trainingSelect} WHERE id = ?`).get(result.lastInsertRowid) }
export function updateTraining(id, trainingId, input) { const existing = db.prepare('SELECT id, rating FROM trainings WHERE id = ? AND facilitator_id = ?').get(trainingId, id); if (!existing) return null; const startDate = input.startDate || input.date; const endDate = input.endDate || startDate; const material = trainingMaterial(input); const rating = input.rating === undefined ? existing.rating : (input.rating === '' || input.rating == null ? null : Number(input.rating)); db.prepare('UPDATE trainings SET name = ?, material = ?, event_date = ?, start_date = ?, end_date = ?, color = ?, organizer = ?, role = ?, category = ?, participant_count = ?, rating = ?, certificate_url = ?, notes = ?, is_catalog_only = ? WHERE id = ?').run(input.name.trim(), material, startDate, startDate, endDate, input.color || '#9f58cc', input.organizer || null, input.role || null, input.category || 'teaching_experience', input.participantCount ?? null, rating, input.certificateUrl || null, input.notes || null, input.catalogOnly ? 1 : 0, trainingId); syncCompetency(id, material); return db.prepare(`${trainingSelect} WHERE id = ?`).get(trainingId) }
export function deleteTraining(id, trainingId) { const result = db.prepare('DELETE FROM trainings WHERE id = ? AND facilitator_id = ?').run(trainingId, id); return result.changes ? { id: Number(trainingId) } : null }
export function attachTrainingCertificate(id, trainingId, url) { const result = db.prepare('UPDATE trainings SET certificate_url = ? WHERE id = ? AND facilitator_id = ?').run(url, trainingId, id); return result.changes ? db.prepare(`${trainingSelect} WHERE id = ?`).get(trainingId) : null }
export function listEducations(id) { return db.prepare('SELECT id, institution, degree, start_date startDate, end_date endDate, graduation_year graduationYear FROM facilitator_educations WHERE facilitator_id = ? ORDER BY COALESCE(end_date, graduation_year || \'-01\') DESC').all(id) }
export function createEducation(id, input) { if (!getFacilitator(id)) return null; const result = db.prepare('INSERT INTO facilitator_educations (facilitator_id, institution, degree, start_date, end_date, graduation_year) VALUES (?, ?, ?, ?, ?, ?)').run(id, input.institution.trim(), input.degree || null, input.startDate || null, input.endDate || null, input.graduationYear ?? (input.endDate ? Number(input.endDate.slice(0, 4)) : null)); return db.prepare('SELECT id, institution, degree, start_date startDate, end_date endDate, graduation_year graduationYear FROM facilitator_educations WHERE id = ?').get(result.lastInsertRowid) }
export function updateEducation(id, educationId, input) { const existing = db.prepare('SELECT id FROM facilitator_educations WHERE id = ? AND facilitator_id = ?').get(educationId, id); if (!existing) return null; db.prepare('UPDATE facilitator_educations SET institution = ?, degree = ?, start_date = ?, end_date = ?, graduation_year = ? WHERE id = ?').run(input.institution.trim(), input.degree || null, input.startDate || null, input.endDate || null, input.graduationYear ?? (input.endDate ? Number(input.endDate.slice(0, 4)) : null), educationId); return db.prepare('SELECT id, institution, degree, start_date startDate, end_date endDate, graduation_year graduationYear FROM facilitator_educations WHERE id = ?').get(educationId) }
export function deleteEducation(id, educationId) { const result = db.prepare('DELETE FROM facilitator_educations WHERE id = ? AND facilitator_id = ?').run(educationId, id); return result.changes ? { id: Number(educationId) } : null }
export function createReview(id, input) { if (!getFacilitator(id)) return null; return transaction(() => { const result = db.prepare('INSERT INTO reviews (facilitator_id, author_name, rating, comment) VALUES (?, ?, ?, ?)').run(id, input.authorName.trim(), input.rating, input.comment.trim()); return db.prepare('SELECT id, author_name authorName, rating, comment, created_at createdAt FROM reviews WHERE id = ?').get(result.lastInsertRowid) }) }
export function createTrainingReview(id, trainingId, input) { const training = db.prepare("SELECT id FROM trainings WHERE id = ? AND facilitator_id = ? AND COALESCE(end_date, event_date) < date('now')").get(trainingId, id); if (!training) throw Object.assign(new Error('Rating hanya dapat diberikan setelah kegiatan selesai.'), { status: 422 }); return transaction(() => { const result = db.prepare('INSERT INTO reviews (facilitator_id, training_id, author_name, rating, comment) VALUES (?, ?, ?, ?, ?)').run(id, trainingId, input.authorName.trim(), input.rating, input.comment.trim()); return db.prepare('SELECT id, author_name authorName, rating, comment, created_at createdAt FROM reviews WHERE id = ?').get(result.lastInsertRowid) }) }
